### ISSUE TITLE
hit rects should be centered

### ISSUE THREAD

**Issue by mick-warehime** [mick-warehime/swmp#28] opened 2017-12-12 15:55 UTC
repro: press 'h' while playing and find a mob. the hit rects are aligned to top left

**Comment by dvirk** [comment] 2017-12-12 17:48
This only seems to be happening when the Mobs are moving diagonally. I think it is because the center of the image is not the Mob's head, so when the image is rotated the head moves around the center point.

**Comment by dvirk** [comment] 2017-12-12 18:32
My next pull request should fix this.

**Comment by dvirk** [comment] 2017-12-12 18:35
Oops I made more changes to the branch before I merged with master. I'll start using better branch names. Now the issue is fixed though.

**Closed by dvirk** 2017-12-12 18:35 UTC
